name: Testing
on:
  workflow_dispatch: 
  push:
    branches:
      - test
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test-artifact:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download -n publish-result -R https://github.com/BusHero/xml.schema -D publish
          ls -la publish
          pwd
      - name: test
        run: ./build.sh RunIntegrationTests
