name: Testing
on:
  push:
    branches:
      - master
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run download -n publish-result -R https://github.com/BusHero/xml.schema -D publish
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Integration Tests
        run: ./build.sh --target RunIntegrationTests
