name: Testing
on:
  workflow_dispatch: 
  push:
    branches:
      - test
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download -n publish-result -R https://github.com/BusHero/xml.schema -D publish
          ls -la publish
          pwd
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
#      - name: Run Integration Tests
#        run: dotnet ./publish/XmlSchemaApi.dll
      - name: test
        run: dotnet test
