name: Build
on:
  push:
  workflow_dispatch: 
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Display Hello, World
        run: echo "Hello, World!"
