name: Testing
on:
  push:
  workflow_dispatch: 
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run download 6226532707 -n publish-result
      - name: list files
        run: ls -l
